# Generated by Django 5.2.8 on 2025-11-13 09:50

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji jako ikona', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Treść')),
                ('excerpt', models.TextField(blank=True, help_text='Wyświetlany na listach', max_length=300, verbose_name='Krótki opis')),
                ('difficulty', models.CharField(choices=[('beginner', '⭐ Podstawy'), ('intermediate', '⭐⭐ Średniozaawansowany'), ('advanced', '⭐⭐⭐ Zaawansowany')], default='beginner', max_length=20, verbose_name='Poziom trudności')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Opublikowano')),
                ('views_count', models.IntegerField(default=0, verbose_name='Liczba wyświetleń')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='blog.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Lekcja',
                'verbose_name_plural': 'Lekcje',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
