# Generated by Django 5.2.8 on 2025-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tytuł')),
                ('description', models.TextField(help_text='Krótki opis zasobu (max 200 znaków)', max_length=200, verbose_name='Opis')),
                ('url', models.URLField(max_length=500, verbose_name='Link')),
                ('resource_type', models.CharField(choices=[('documentation', '📖 Dokumentacja'), ('tutorial', '🎥 Tutorial'), ('tool', '🛠️ Narzędzie'), ('article', '📄 Artykuł'), ('course', '🎓 Kurs'), ('other', '🔗 Inne')], default='other', max_length=20, verbose_name='Typ zasobu')),
                ('is_external', models.BooleanField(default=True, help_text='Czy link prowadzi na zewnętrzną stronę', verbose_name='Zewnętrzny link')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Zasób',
                'verbose_name_plural': 'Zasoby',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
