# Generated by Django 5.2.8 on 2025-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '⭐ Początkujący'), ('intermediate', '⭐⭐ Średniozaawansowany'), ('advanced', '⭐⭐⭐ Zaawansowany')], default='beginner', max_length=20, verbose_name='Poziom trudności'),
        ),
    ]
