# Generated by Django 5.2.8 on 2025-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('documentation', '📖 Dokumentacja'), ('tutorial', '🎥 Tutoriale'), ('tool', '🛠️ Narzędzia'), ('article', '📄 Artykuły'), ('course', '🎓 Kursy'), ('other', '🔗 Inne')], default='other', max_length=20, verbose_name='Typ zasobu'),
        ),
    ]
